---
language: ruby
sudo: false
addons:
  apt:
    packages:
      - libaugeas-dev
cache: bundler
bundler_args: --without system_tests
script: ["bundle exec rake validate", "bundle exec rake lint", "bundle exec rake spec SPEC_OPTS='--format documentation'"]
matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0"
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "Mzp+uK8zlxCBt1iVxoROZO87Kogax82M0ZYaX/AwkUcB5M279YoRWAaIk0WUvag+ifh/ltxjaB9QJKRxZD3ysUZajKqu9gJZuv2pANShLiTVOGxsvs/pyXDc56ynmbz7XP5SAwOyW7eJp5l14RpwKWm0mF+Ft2TQFAMbLrRHo1w="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.1.7
